version: '3'
services:
  db:
    image: 'mysql/mysql-server:5.7'
    restart: unless-stopped
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "qq1203943228"
    networks:
      - net-spring-db
    user: root
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/my.cnf:/etc/my.cnf
      - ./api/sql:/docker-entrypoint-initdb.d/
    ports:
      - "3333:3306"
  api:
    image: 'fulln/ftz:1.0.0'
    container_name: ftz
    ports:
      - "82:8082"
    networks:
      - net-spring-db
    volumes:
      - ./source/:/opt/source/
      - ./logs/api/:/opt/logs/
      - /var/run/docker.sock
      - /bin/docker
    depends_on:
      - db
      - redis
  redis:
    restart: unless-stopped
    image: redis:4.0.9
    container_name: redis
    #    command: redis-server /etc/redis/redis.conf
    command: redis-server --requirepass "ZV5ut2FNPp/5iqE1l5feIg=="
    networks:
      - net-spring-db
    volumes:
      -  ./redis/redis.conf:/etc/redis/redis.conf
      -  ./redis/data:/data
    ports:
      - "6333:6379"
networks:
  net-spring-db:
    driver: bridge